# Generated by Django 4.1.7 on 2023-04-21 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
