# Generated by Django 4.2.3 on 2023-07-23 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_event_profile_task_remove_login_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.task'),
        ),
    ]
